Concentration to AQI calculation for US and China.
adafruit/Adafruit_PM25AQI pull request #12
Opened 2022-07-23 12:09 UTC by jiangyi1985

Concentration to AQI calculation for US and China.
Add fail reason and verbose info.
Check start byte more strickly.
Parse version and error code.

2022-07-23 12:11 UTC, jiangyi1985 commented
![image](https://user-images.githubusercontent.com/11713383/180604342-d99c83c3-a6a6-4d9f-8eba-1abd2d9f729b.png)

2023-11-01 22:29 UTC, brentru commented
@tyeth  Want to take a look at this?

2023-11-03 13:21 UTC, tyeth commented
Hi @jiangyi1985 and thanks for your contribution!

I saw that the way your segmenting for PM2.5 (12 and <12.1 meant to be up to and including 12) compared to PM10 (55 + 55 meant to be upto and including 54), seem to be different, the latter should probably follow the former.
![image](https://github.com/adafruit/Adafruit_PM25AQI/assets/6692083/7ead862a-7ddb-470a-8512-80b03fbd2786)

I'm using this reference from the US EPA https://www.airnow.gov/sites/default/files/2020-05/aqi-technical-assistance-document-sept2018.pdf however I cannot find a reference for calculating the Chinese AQI. Most information seems very old, like before 2018, and unofficial.
Where did you get the values for the AQI for China?

2023-11-06 07:33 UTC, jiangyi1985 commented
@tyeth When I wrote the code last year, I referenced this wiki page:
https://en.wikipedia.org/wiki/Air_quality_index

Now that I've checked where the data of China & US are referenced, the sources seem to be legit.

Here's the reference of China's data:
https://www.mee.gov.cn/ywgz/fgbz/bz/bzwb/jcffbz/201203/t20120302_224166.shtml

2023-11-09 01:20 UTC, tyeth requested changes
Changes requested, but minor.

2023-11-09 01:20 UTC, tyeth commented on Adafruit_PM25AQI.cpp
> +    AQI = linear(50, 0, 55, 0, c);
Should this be 54.1, or should the PM2.5 code be updated? They follow similar but different approaches for the breakpoints. This is not the only example of this, but rather than mark every line please have another look at all the breakpoints / conditionals

2023-11-09 01:20 UTC, tyeth commented on Adafruit_PM25AQI.cpp
> +    AQI = linear(50, 0, 55, 0, c);
Actually in hindsight I'm not so sure now, maybe this is fine. There is a gap between 54 and 55, you've closed it, and there is no guidance for that really.

2023-11-09 01:20 UTC, tyeth commented on Adafruit_PM25AQI.cpp
> +  data->datasum = sum;
It doesn't make sense for to be here as then the following IF is negated. I wonder whether you meant to save it for printing later, probably it looks less nice setting in two places instead.

2023-11-09 01:20 UTC, tyeth commented on Adafruit_PM25AQI.cpp
> +  data->aqi_pm25_us = pm25_aqi_us(data->pm25_env);
I wonder whether we should do this conversion immediately for all AQI values, or if it should be left up to the user (passing in current data value). Saves a few cycles, but not really too fussed as it's a PM2.5/AQI library.
Leave it in for now unless @brentru says otherwise :)

2023-11-09 01:20 UTC, tyeth commented on Adafruit_PM25AQI.h
> +  // when copy data from int8 array to this struct with memcpy, error_code need
Please clean this up

2023-11-09 01:20 UTC, tyeth commented on examples/PM25_test/PM25_test.ino
This is a bit badly formatted (debug comments - maybe remove them and the print function)
@brentru I'm not sure on policy / preference, would a debug related printInfo function be appreciated in the library, or just example, or neither?

2024-12-18 13:05 UTC, jiangyi1985 commented on examples/PM25_test/PM25_test.ino
removed

2024-12-18 13:05 UTC, jiangyi1985 commented on Adafruit_PM25AQI.h
> +  // when copy data from int8 array to this struct with memcpy, error_code need
comments cleaned up

2024-12-18 13:05 UTC, jiangyi1985 commented on Adafruit_PM25AQI.cpp
> +  data->datasum = sum;
removed

2024-12-18 13:07 UTC, jiangyi1985 commented on Adafruit_PM25AQI.cpp
> +  data->aqi_pm25_us = pm25_aqi_us(data->pm25_env);
not changed

2024-12-18 13:07 UTC, jiangyi1985 commented on Adafruit_PM25AQI.cpp
> +    AQI = linear(50, 0, 55, 0, c);
not changed

2024-12-19 12:12 UTC, jiangyi1985 commented
@tyeth Conflict resolved

2024-12-20 23:46 UTC, tyeth commented
Thanks for the updates! I've run out of time this week and am off for a bit.
@brentru if you want to have a look, otherwise I'm back January 6th, but
there's also a very small chance I'll test it over the holiday period.

On Thu, 19 Dec 2024 at 12:13, Ivan Jiang ***@***.***> wrote:

> @tyeth <https://github.com/tyeth> Conflict resolved
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/adafruit/Adafruit_PM25AQI/pull/12#issuecomment-2553629076>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ABTBZ47QQSHXKWNHWBHFFU32GKZ5LAVCNFSM6AAAAABT2U6IFOVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDKNJTGYZDSMBXGY>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-12-23 16:01 UTC, brentru approved these changes
@jiangyi1985 This PR looks good and you've made the corrections Tyeth asked. I don't see any glaring issues with it and will merge in.

2024-12-23 16:01 UTC, merged